application: telegraphchristmas
version: 1
runtime: python
api_version: 1

# TEMP - DURING DEVELOPMENT ONLY!
default_expiration: "1m"

handlers:
 - url: /js
   static_dir: js

 - url: /css
   static_dir: css

 - url: /media
   static_dir: media

 - url: /cache.manifest
   mime_type: text/cache-manifest
   static_files: cache.manifest
   upload: cache.manifest

 - url: /static
   static_dir: static

 - url: /images
   static_dir: images

 - url: /fonts/tangerine_regular-webfont.ttf
   mime_type: font/ttf
   static_files: fonts/tangerine_regular-webfont.ttf
   upload: fonts/tangerine_regular-webfont.ttf

 - url: /fonts/tangerine_regular-webfont.svg
   static_files: fonts/tangerine_regular-webfont.svg
   upload: fonts/tangerine_regular-webfont.svg

 - url: /fonts/tangerine_regular-webfont.woff
   mime_type: font/x-woff
   static_files: fonts/tangerine_regular-webfont.woff
   upload: fonts/tangerine_regular-webfont.woff

 - url: /fonts
   static_dir: fonts

 - url: /.*
   script: showcard.py


