application: telegraphchristmas
version: 1
runtime: python
api_version: 1

handlers:
 - url: /js
   static_dir: js
 - url: /css
   static_dir: css
 - url: /media
   static_dir: media
 - url: /cache.manifest
   static_files: cache.manifest
   mime_type: text/cache-manifest
   upload: static/cache.manifest
 - url: /static
   static_dir: static
 - url: /.*
   script: showcard.py


